name: "@ubiquity-os-marketplace/daemon-pull-review"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "Signature sent from the Kernel"
      command:
        description: "Command"

jobs:
  compute:
    name: "Pull review"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: execute directive
        run: node ./dist/index.js
        id: daemon-pull-review
        env:
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
          PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          UBIQUITY_OS_APP_NAME: ${{ secrets.UBIQUITY_OS_APP_NAME }}
